apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
spec:
  containers:
  - name: busybox-pod
    image: busybox:unstable-musl
    command: 
    - /bin/sh
    - -c
    - |
      while true; do
        date
        sleep 10
      done
    ports:
    - containerPort: 80
    volumeMounts:
    - name: vol-busybox
      mountPath: /data
  volumes:
  - name: vol-busybox
    hostPath: 
      path: /Data/busybox
      type: Directory
  