apiVersion: v1
kind: Pod
metadata:
  name: webpod
  labels:
    app: website
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    command: ["/bin/sh", "-c"]
    args:
      - echo '<!DOCTYPE html>
        <html>
        <head>
          <title>DevOps</title>
        </head>
        <body style="text-align:center; margin-top:100px; font-family:sans-serif;">
        <h1>AKHIL K</h1>
        <p>DevOps Engineer</p>
        </body>
       </html>' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;';

---
apiVersion: v1
kind: Service
metadata:
  name: website-service
spec:
  type: NodePort
  selector:
    app: website
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008