apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
spec:
  containers:
  - name: jenkins-pod
    image: jenkins/jenkins:latest-jdk25
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: vol-jenkins
      mountPath: /var/jenkins_data
  volumes:
  - name: vol-jenkins
    hostPath: 
      path: /Data/jenkins
      type: Directory