apiVersion: v1
kind: Pod
metadata:
  name: jkwr-pod
spec:
  containers:
  - name: jenkinspod
    image: jenkins/jenkins:Its
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: vol-jkwr
      mountPath: /var/jenkins_home
  containers:
  - name: wordpresspod
    image: wordpress:apache
    ports:
    - containerPort: 80
    volumeMounts:
    - name: vol-jkwr
      mountPath: /var/www/html
  volumes:
  - name: vol-jkwr
    hostPath: 
      path: /data/jkwr
      type: DirectoryOrCreate