apiVersion: v1
kind: Secret
metadata:
  name: newsecret
data:
  .dockerconfigjson: ewogICAiYXV0aHMiOiB7CiAgICAgImh0dHA6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjogewogICAgICJ1c2VybmFtZSI6ICJha2hpYWtoaTEiLAogICAgICJwYXNzd29yZCI6ICJBa2hpbEAyMDA0IiwKICAgICAiZW1haWwiOiAiYWtoaWxrYWxhZGhhcmFuMjVAZ21haWwuY29tIiwKICAgICAiYXV0aCI6ICJCQVNFNjQoWVd0b2FXRnJhR2t4T2tGcmFHbHNRREl3TURRPSkiCiAgICAgfQogICB9Cn0K
type: kubernetes.io/dockerconfigjson
